### ISSUE TITLE
"delQuestionnaire" löscht Bogen nicht wenn Status "abgeschlossen"

### ISSUE THREAD

**Issue by BenjaminWilliamAtkins** [real-Shurakra/LehrerbewertungsWebseite#23]
Die Methode "delQuestionnaire" löscht den Bogen nicht wenn der Status "abgeschlossen" ist
Ich konnte alle Bögen mit offenem Status löschen, doch bei den abgeschlossenen ist der return immer "false".

**Comment by real-Shurakra** [comment]
Bitte prüfen.
Wenn's nicht klappt bitte genau beschreiben wie du den Status "Abgeschlossen" erstellst. Die Datenbank bildet das nicht ab.

**Comment by BenjaminWilliamAtkins** [comment]
Status abgeschlossen heißt einfach nur, dass keine Codes mehr vorhanden sind. Den Status ermittle ich lediglich aus der Anzahl der verbliebenen Codes. Wenn dieser = 0 ist, ist der Status abgeschlossen. Soweit ich mich erinnere war das auch kein Problem mehr. Jetzt werden keine Bögen gelöscht, die mindestens einen Satz mit antworten enthalten. Also wenn bereits mindestens einmal Punkte vergeben wurden, Dann löscht er den Bogen nicht mehr. Lass uns das am besten mal gemeinsam ansehen. Ich merge heute erstmal meinen Branch in dev.

**Comment by real-Shurakra** [comment]
#
Duplicate of #24
see: 6707d379daf2d14dac273c20c46fc98e1a53adc8
