### ISSUE TITLE
"delQuestionnaire" löscht lediglich die Codes wenn der Bogen Antworten enthält

### ISSUE THREAD

**Issue by BenjaminWilliamAtkins** [real-Shurakra/LehrerbewertungsWebseite#24]
Die Methode "delQuestionnaire" gibt false zurück sobald der Bogen Antworten enthält. Lediglich die Codes werden gelöscht.

**Comment by real-Shurakra** [comment]
Problem war, dass die Antworten und Verbesserungsvorschläge vorher nicht gelöscht wurden.
Habe ich behoben bitte Testen.

**Comment by BenjaminWilliamAtkins** [comment]
Funktioniert noch nicht, auch nicht wenn das Ding keine Antworten hat gibt es false zurück.

**Comment by real-Shurakra** [comment]
implementiert in: 6707d379daf2d14dac273c20c46fc98e1a53adc8
