### ISSUE TITLE
Nach Abgabe eines Bogens im Schülerbereich tritt Fehler im GUI auf wenn Lehrer angemeldet

### ISSUE THREAD

**Issue by BenjaminWilliamAtkins** [real-Shurakra/LehrerbewertungsWebseite#33]
Ich weiß nicht genau, ob der Fehler auch Eintritt wenn der Lehrer an einem unabhängigen Client angemeldet ist.
Den Test habe ich mit zwei Tabs des selben Browsers durchgeführt, deshalb kann ich das noch nicht beurteilen.

Jedenfalls konnte ich kurz nachdem ich auf der Schülerseite einen ausgefüllten Bogen abgeschickt hatte, auf der Lehrerseite den Bogen nicht mehr öffnen. Ich musste mich erst wieder aus und einloggen damit es funktionierte.

Der Fehler hat jedoch keine nachhaltigen Auswirkungen auf die Daten. Nach der erneuten Anmeldung sieht alles soweit richtig aus.

Das sollten wir uns jedenfalls mal zu zweit angucken, vielleicht fällt dir ja eine passende Antwort dazu ein.

**Comment by real-Shurakra** [comment]
Schreiben einer php Methode die prüft ob Nutzer noch angemeldet ist.
JS Seitig muss der benutzer dann abgemeldet werden wenn der nutzer auf php ebene nicht angelemdet ist.
Dies sollte über einen Timer in einer festgelegten Zeit überprüft werden.

Got it! (⌐■_■)

**Comment by real-Shurakra** [comment]
Wurde in commit fb1c355b783f94d111f64e524b44c31109c664a2 programmiert. 
Siehe commitmassage für weitere Infos.

**Comment by real-Shurakra** [comment]
Ich denke, das Thema ist durch.
