### ISSUE TITLE
Add in master->main.php

### ISSUE THREAD

**Issue by real-Shurakra** [real-Shurakra/LehrerbewertungsWebseite#35]
<table>
  <tr>
    <th>Implementiert </th>
    <th>Bezeichnung</th>
    <th>Adminonly </th>
    <th>Funktion</th>
  </tr>
<tr>
	<td>✔</td>
	<td>Benutzer Login</td>
	<td>❌</td>
	<td>
		<details>
			<summary>loginUser()</summary>
			<ul>
				<li>
					Parameter:
					<ul>
						<li>mode = "loginUser"</li>
						<li>mail = <i>mail des Benutzers als string</li>
						<li>passwort = <i>Passwort des Benutzers als string</li>
					</ul>
				</li>
				<li>
					Return:
					<ul>
						<li>array('returncode'=>true, 'returnvalue'=>string)<br>Benutzer gefunden.</li>
						<li>array('returncode'=>true, 'returnvalue'=>false)<br>Benutzer nicht gefunden</li>
					</ul>
				</li>
				<li>
					Exception:
					<ul>
						<li>array('returncode'=>false, 'returnvalue'=>string)<br>'returnvalue' enthält Name der Log Datei</li>
					</ul>
				</li>
			<ul>
		</details>
	</td>
</tr>
<tr>
	<td>✔</td>
	<td>Neuen User anlegen</td>
	<td>✔</td>
	<td>
		<details>
			<summary>addUser()</summary>
			<ul>
				<li>
					Parameter:
					<ul>
						<li>mode = "addUser"</li>
						<li>mail = <i>mail des neuen Benutzers</i></li>
						<li>firstname = <i>Vorname des neuen Benutzers</i></li>
						<li>lastname = <i>Nachname des neuen Benutzers</i></li>
						<li>defaultPassword = <i>Das vom Admin vergebene Password</i></li>
					</ul>
				</li>
				<li>
					Return:
					<ul>
						<li>array('returncode'=>true,'returnvalue'=>true)<br>User angelegt</li>
						<li>array('returncode'=>true,'returnvalue'=>false)<br>User nicht angelegt. Password verkehrt?</li>
					</ul>
				</li>
				<li>
					Exception:
					<ul>
						<li>array('returncode'=>false, 'returnvalue'=>string)<br>'returnvalue' enthält Name der Log Datei</li>
					</ul>
				</li>
			<ul>
		</details>
	</td>
</tr>
<tr>
	<td>✔</td>
	<td>Passwort ändern</td>
	<td>❌</td>
	<td>
		<details>
			<summary>changePassword()</summary>
			<ul>
				<li>
					Parameter:
					<ul>
						<li>mode = "changePassword"</li>
						<li>oldPasswort = <i>Altes Benutzerpasswort</i></li>
						<li>newPasswort = <i>Neues Benutzerpasswort</i></li>
					</ul>
				</li>
				<li>
					Return:
					<ul>
						<li>array ('returncode'=>true,'returnvalue'=>boolean)<br>returnvalue true wenn geändert sonst false. Password verkehrt?</li>
					</ul>
				</li>
				<li>
					Exception:
					<ul>
						<li>array('returncode'=>false, 'returnvalue'=>string)<br>'returnvalue' enthält Name der Log Datei</li>
					</ul>
				</li>
			<ul>
		</details>
	</td>
</tr>
<tr>
	<td>✔</td>
	<td>Passwort resetten</td>
	<td>✔</td>
	<td>
		<details>
			<summary>resetPassword()</summary>
			<ul>
				<li>
					Parameter:
					<ul>
						<li>mode = "resetPassword"</li>
						<li>password= <i>Passwort des aktuellen Root Users</i></li>
						<li>resetUser= <i>Benutzername des rückzusetzenden Users</i></li>
						<li>stdPassword= <i>Neues Password für den User</i></li>
					</ul>
				</li>
				<li>
					Return:
					<ul>
						<li>array ('returncode'=>true,'returnvalue'=>true)<br>geändert</li>
						<li>
							array ('returncode'=>true,'returnvalue'=>integer)
							<ul>
								<li>3 - Passwort zu kurz. Min. 8 Zeichen</li>
								<li>4 - Passwort enthält Leerzeichen</li>
								<li>5 - Passwort enthält Semikolon</li>
							</ul>
						</li>
					</ul>
				</li>
				<li>
					Exception:
					<ul>
						<li>array('returncode'=>false, 'returnvalue'=>string)<br>'returnvalue' enthält Name der Log Datei</li>
					</ul>
				</li>
			<ul>
		</details>
	</td>
</tr>
<tr>
	<td>✔</td>
	<td>Login Zustand erfragen</td>
	<td>❌</td>
	<td>
		<details>
			<summary>checkLogin()</summary>
			<ul>
				<li>
					Parameter:
					<ul>
						<li>mode = "checkLogin"</li>
					</ul>
				</li>
				<li>
					Return:
					<ul>
						<li>
							array ('returncode'=>true,'returnvalue'=>boolean)
							<ul>
								<li>true - eingeloggt</li>
								<li>false - nicht eingeloggt</li>
							</ul>
						</li>
					</ul>
				</li>
				<li>
					Exception:
					<ul>
						<li>array('returncode'=>false, 'returnvalue'=>string)<br>'returnvalue' enthält Name der Log Datei</li>
					</ul>
				</li>
			<ul>
		</details>
	</td>
</tr>
<tr>
	<td>✔</td>
	<td>User löschen</td>
	<td>✔</td>
	<td>
		<details>
			<summary>deleteUser()</summary>
			<ul>
				<li>
					Parameter:
					<ul>
						<li>mode = "deleteUser"</li>
						<li>password= _Passwort des aktuellen Root Users_</li>
						<li>deleteThis= _Benutzername des zu löschenden Users_</li>
					</ul>
				</li>
				<li>
					Return:
					<ul>
						<li>array ('returncode'=>true,'returnvalue'=>true)<br>Benutzer gelöscht</li>
						<li>
							array ('returncode'=>true,'returnvalue'=>integer)
							<ul>
								<li>3 - Passwort zu kurz. Min. 8 Zeichen</li>
								<li>4 - Passwort enthält Leerzeichen</li>
								<li>5 - Passwort enthält Semikolon</li>
								<li>6 - Zu löschenden Benutzer nicht gefunden</li>
								<li>7 - Zu löschender Benutzer nach Löschung noch in Datenbank</li>
							</ul>
						</li>
					</ul>
				</li>
				<li>
					Exception:
					<ul>
						<li>array('returncode'=>false, 'returnvalue'=>string)<br>'returnvalue' enthält Name der Log Datei</li>
					</ul>
				</li>
			<ul>
		</details>
	</td>
</tr>
<tr>
	<td>✔</td>
	<td>Fach anlegen</td>
	<td>✔</td>
	<td>
		<details>
			<summary>addSubject()</summary>
			<ul>
				<li>
					Parameter:
					<ul>
						<li>mode = "addSubject"</li>
						<li>subjectName = <i>Name des neuen Fachs</i></li>
					</ul>
				</li>
				<li>
					Return:
					<ul>
						<li>array('returncode'=>true, 'returnvalue'=>true)<br>Fach angelegt</li>
						<li>array('returncode'=>true, 'returnvalue'=>false)<br>User ist nicht root</li>
					</ul>
				</li>
				<li>
					Exception:
					<ul>
						<li>array('returncode'=>false, 'returnvalue'=>$error->getMessage())<br>Gibt den Fehler direckt aus</li>
					</ul>
				</li>
			<ul>
		</details>
	</td>
</tr>
<tr>
	<td>✔</td>
	<td>Fach soft-delete umschalten</td>
	<td>✔</td>
	<td>
		<details>
			<summary>changeSubjectDelete()</summary>
			<ul>
				<li>
					Parameter:
					<ul>
						<li>mode = "changeSubjectDelete"</li>
						<li>subjectName = <i>Name des Fachs</i></li>
					</ul>
				</li>
				<li>
					Return:
					<ul>
						<li>array('returncode'=>true, 'returnvalue'=>true)<br>Fach angelegt</li>
						<li>array('returncode'=>true, 'returnvalue'=>false)<br>User ist nicht root</li>
					</ul>
				</li>
				<li>
					Exception:
					<ul>
						<li>array('returncode'=>false, 'returnvalue'=>$error->getMessage())<br>Gibt den Fehler direckt aus</li>
					</ul>
				</li>
			<ul>
		</details>
	</td>
</tr>
<tr>
	<td>✔</td>
	<td>Klasse anlegen</td>
	<td>✔</td>
	<td>
		<details>
			<summary>addClass()</summary>
			<ul>
				<li>
					Parameter:
					<ul>
						<li>mode = "addClass"</li>
						<li>className = <i>Name der Klasse</i></li>
						<li>studentCount = <i>Schüleranzahl</i></li>
					</ul>
				</li>
				<li>
					Return:
					<ul>
						<li>array('returncode'=>true, 'returnvalue'=>true)<br>Fach angelegt</li>
						<li>array('returncode'=>true, 'returnvalue'=>false)<br>User ist nicht root</li>
					</ul>
				</li>
				<li>
					Exception:
					<ul>
						<li>array('returncode'=>false, 'returnvalue'=>$error->getMessage())<br>Gibt den Fehler direckt aus</li>
					</ul>
				</li>
			<ul>
		</details>
	</td>
</tr>
<tr>
	<td>✔</td>
	<td>Klasse soft-delete</td>
	<td>✔</td>
	<td>
		<details>
			<summary>changeClassDelete()</summary>
			<ul>
				<li>
					Parameter:
					<ul>
						<li>mode = "changeClassDelete"</li>
						<li>className = <i>Name der Klasse</i></li>
					</ul>
				</li>
				<li>
					Return:
					<ul>
						<li>array('returncode'=>true, 'returnvalue'=>true)<br>Fach angelegt</li>
						<li>array('returncode'=>true, 'returnvalue'=>false)<br>User ist nicht root</li>
					</ul>
				</li>
				<li>
					Exception:
					<ul>
						<li>array('returncode'=>false, 'returnvalue'=>$error->getMessage())<br>Gibt den Fehler direckt aus</li>
					</ul>
				</li>
			<ul>
		</details>
	</td>
</tr>
<tr>
	<td>✔</td>
	<td>Alle Benutzer auslesen</td>
	<td>✔</td>
	<td>
		<details>
			<summary>getAllUser()</summary>
			<ul>
				<li>
					Parameter:
					<ul>
						<li>mode = "getAllUser"</li>
					</ul>
				</li>
				<li>
					Return:
					<ul>
						<li>array ('rc'=>true,'rv'=>array)</li>
					                <ul>
                                                            <li>array(array(), array(), ... )</li>
					                        <ul>
                                                                    <li>mail - Benutzer Mail Adresse</li>
                                                                    <li>0 - Benutzer Mail Adresse</li>
                                                                    <li>isroot - 1 wenn Benutzer Root sonst 0</li>
                                                                    <li>1 - 1 wenn Benutzer Root sonst 0</li>
                                                                    <li>creationdate - Erstellzeitpunkt als Timestamp</li>
                                                                    <li>2 - Erstellzeitpunkt als Timestamp</li>
					                        </ul>
					                </ul>
						<li>array ('rc'=>true,'rv'=>false)</li>
					</ul>
				</li>
				<li>
					Exception:
					<ul>
						<li>array('returncode'=>false, 'returnvalue'=>string)<br>'returnvalue' enthält Name der Log Datei</li>
					</ul>
				</li>
			<ul>
		</details>
	</td>
</tr>
</table>

**Comment by real-Shurakra** [comment]
### Benutzer Login
- Parameter :
  - mode = "loginUser";
  - mail = _mail des Benutzers als string_
  - passwort = _Passwort des Benutzers als string_
- Return:
  - array('returncode'=>true, 'returnvalue'=>string) - Benutzer gefunden. returnvalue ist timestamp des letzten Logins
  - array('returncode'=>true, 'returnvalue'=>false) - Benutzer nicht gefunden
- Exception:
  - array('returncode'=>false, 'returnvalue'=>string) - 'returnvalue' enthält Name der Log Datei

### Neuen User hinzufügen
- Parameter :
  - mode = "addUser"
  - mail = _mail des neuen Benutzers_
  - firstname = _Vorname des neuen Benutzers_
  - lastname = _Nachname des neuen Benutzers_
  - defaultPassword = _Das vom Admin vergebene Password_
- Return:
  - array('returncode'=>true,'returnvalue'=>true) - User angelegt
  - array('returncode'=>true,'returnvalue'=>false) - User nicht angelegt. Password verkehrt?
- Exception:
  - array('returncode'=>false, 'returnvalue'=>string) - 'returnvalue' enthält Name der Log Datei

### Passwort ändern
- Parameter :
  - mode = "changePassword"
  - oldPasswort = _Altes Benutzerpasswort_
  - newPasswort = _Neues Benutzerpasswort_
- Return:
  - array ('returncode'=>true,'returnvalue'=>boolean) - returnvalue true wenn geändert sonst false. Password verkehrt?
- Exception:
  - array('returncode'=>false, 'returnvalue'=>string) - 'returnvalue' enthält Name der Log Datei

**Comment by BenjaminWilliamAtkins** [comment]
Ok, kannst du noch eine Methode schreiben die alle in der Datenbank vorhandenen User anzeigt, damit man diese auch bearbeiten kann?

**Comment by real-Shurakra** [comment]
> Ok, kannst du noch eine Methode schreiben die alle in der Datenbank vorhandenen User anzeigt, damit man diese auch bearbeiten kann?

Welche Informationen benötigst du vom Usereintrag?

**Comment by real-Shurakra** [comment]
New Commit:
b624a2aa556aafce116098652a4e26cfa6fb4127

**Comment by real-Shurakra** [comment]
Nach Absprache in MS Teams benötigt die Funktion für das root auslesen der Benutzer neben dem Nutzernamen noch die Information ob ein Nutzer root ist und den Timestamp der Benutzererstellung.

Für den Timestamp wird die die Account Tabelle der Datenbank um das Erstell Datum erweitert.

**Comment by real-Shurakra** [comment]
Nach Absprache voraussichtlicher Termin am 12.01 Nachmittags zwecks Koordinierung des Updates.

**Comment by real-Shurakra** [comment]
Die Funktionen wurde umgesetzt
